# Generated by Django 6.0.5 on 2026-05-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('bse_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('mcap_cr', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('is_nifty50', models.BooleanField(default=False)),
                ('is_nifty500', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField(null=True)),
                ('market_cap_cr', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='companies.company')),
            ],
            options={
                'db_table': 'daily_prices',
                'ordering': ['-date'],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('period', models.CharField(choices=[('annual', 'Annual'), ('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4')], default='annual', max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('other_income', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('pbt', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('pat', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('eps', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('current_liabilities', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('reserves', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('cash_equivalents', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('debtors', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('cfo', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('capex', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('fcf', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('promoter_holding', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('promoter_pledged', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('fii_holding', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('dii_holding', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(default='bse_xbrl', max_length=30)),
                ('raw_data', models.JSONField(default=dict)),
                ('filing_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='companies.company')),
            ],
            options={
                'db_table': 'financial_statements',
                'ordering': ['-fiscal_year', 'period'],
                'unique_together': {('company', 'fiscal_year', 'period')},
            },
        ),
    ]
