# Generated by Django 6.0.5 on 2026-05-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('flag_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('med', 'Medium'), ('low', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='companies.company')),
            ],
            options={
                'db_table': 'red_flags',
                'ordering': ['severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorMedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('pe_median', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('pb_median', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('roe_median', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('roce_median', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('npm_median', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ebm_median', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('de_median', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sector_medians',
                'unique_together': {('sector', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('narrative', models.TextField()),
                ('model_used', models.CharField(max_length=60)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='companies.company')),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['-updated_at'],
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('pe_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ev_ebitda', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_sales', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('roce', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('roa', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ebitda_margin', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ebit_margin', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('net_margin', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('debt_equity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_debt_ebitda', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('interest_coverage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('asset_turnover', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('inventory_days', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('debtor_days', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('dividend_yield', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('eps_growth_yoy', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('revenue_growth_yoy', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('promoter_holding', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('promoter_pledged', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('fcf_yield', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='companies.company')),
            ],
            options={
                'db_table': 'company_ratios',
                'ordering': ['-fiscal_year'],
                'unique_together': {('company', 'fiscal_year')},
            },
        ),
    ]
